# Generated by Django 5.2.6 on 2025-10-14 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('amount_inserted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inserted_details', models.CharField(max_length=255)),
                ('change_returned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_details', models.CharField(max_length=255)),
            ],
        ),
    ]
